# Generated by Django 5.2.1 on 2025-07-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table2A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('demand_forecast', models.FloatField(blank=True, null=True)),
                ('demand_met', models.FloatField(blank=True, null=True)),
                ('shortage', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Table2C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('morning_peak', models.FloatField(blank=True, null=True)),
                ('evening_peak', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
