# Generated by Django 5.2.1 on 2025-07-30 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NRDCReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'NRDC Report',
                'verbose_name_plural': 'NRDC Reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='Table2AData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('thermal', models.FloatField(blank=True, null=True)),
                ('hydro', models.FloatField(blank=True, null=True)),
                ('gas_naptha_diesel', models.FloatField(blank=True, null=True)),
                ('solar', models.FloatField(blank=True, null=True)),
                ('wind', models.FloatField(blank=True, null=True)),
                ('other_biomass_co_gen_etc', models.FloatField(blank=True, null=True)),
                ('total_generation', models.FloatField(blank=True, null=True)),
                ('drawal_sch_net_mu', models.FloatField(blank=True, null=True)),
                ('act_drawal_net_mu', models.FloatField(blank=True, null=True)),
                ('ui_net_mu', models.FloatField(blank=True, null=True)),
                ('requirement_net_mu', models.FloatField(blank=True, null=True)),
                ('shortage_net_mu', models.FloatField(blank=True, null=True)),
                ('consumption_net_mu', models.FloatField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_2a_data', to='nrldc.nrdcreport')),
            ],
            options={
                'verbose_name': 'Table 2A Data',
                'verbose_name_plural': 'Table 2A Data',
            },
        ),
        migrations.CreateModel(
            name='Table2CData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('max_demand_met_of_the_day', models.FloatField(blank=True, null=True)),
                ('time_max_demand_met', models.CharField(blank=True, max_length=50, null=True)),
                ('shortage_during_max_demand', models.FloatField(blank=True, null=True)),
                ('requirement_at_max_demand', models.FloatField(blank=True, null=True)),
                ('max_requirement_of_the_day', models.FloatField(blank=True, null=True)),
                ('time_max_requirement', models.CharField(blank=True, max_length=50, null=True)),
                ('shortage_during_max_requirement', models.FloatField(blank=True, null=True)),
                ('demand_met_at_max_requirement', models.FloatField(blank=True, null=True)),
                ('min_demand_met', models.FloatField(blank=True, null=True)),
                ('time_min_demand_met', models.CharField(blank=True, max_length=50, null=True)),
                ('ace_max', models.FloatField(blank=True, null=True)),
                ('ace_min', models.FloatField(blank=True, null=True)),
                ('time_ace', models.CharField(blank=True, max_length=50, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_2c_data', to='nrldc.nrdcreport')),
            ],
            options={
                'verbose_name': 'Table 2C Data',
                'verbose_name_plural': 'Table 2C Data',
            },
        ),
    ]
