# Generated by Django 5.2.1 on 2025-07-30 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrldc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nrdcreport',
            options={'verbose_name': 'NRDC Report', 'verbose_name_plural': 'NRDC Reports'},
        ),
    ]
