# Generated by Django 5.2.1 on 2025-07-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrldc', '0002_alter_nrdcreport_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='table2cdata',
            name='unused_col',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
